### ISSUE TITLE
Feedback Request: Python 05 - 08

### ISSUE THREAD

**Issue by QuincyTjia** [TechGrounds-Cloud8/cloud8-QuincyTjia#45]
**Feedback Request [Python 05 - 08]**
Permalink to file: https://github.com/TechGrounds-Cloud8/cloud8-QuincyTjia/blob/8d669c3af700dc77de5b65320b99e91a2b4e6e02/07_Python_01/PRG-05-Conditions1.py

https://github.com/TechGrounds-Cloud8/cloud8-QuincyTjia/blob/8d669c3af700dc77de5b65320b99e91a2b4e6e02/07_Python_01/PRG-05-Conditions2.py

https://github.com/TechGrounds-Cloud8/cloud8-QuincyTjia/blob/8d669c3af700dc77de5b65320b99e91a2b4e6e02/07_Python_01/PRG-06-Functions1.py

https://github.com/TechGrounds-Cloud8/cloud8-QuincyTjia/blob/8d669c3af700dc77de5b65320b99e91a2b4e6e02/07_Python_01/PRG-06-Functions2.py

https://github.com/TechGrounds-Cloud8/cloud8-QuincyTjia/blob/8d669c3af700dc77de5b65320b99e91a2b4e6e02/07_Python_01/PRG-07-Lists1.py

https://github.com/TechGrounds-Cloud8/cloud8-QuincyTjia/blob/8d669c3af700dc77de5b65320b99e91a2b4e6e02/07_Python_01/PRG-07-Lists2.py

https://github.com/TechGrounds-Cloud8/cloud8-QuincyTjia/blob/8d669c3af700dc77de5b65320b99e91a2b4e6e02/07_Python_01/PRG-08-Key-value%20pairs1.py

https://github.com/TechGrounds-Cloud8/cloud8-QuincyTjia/blob/8d669c3af700dc77de5b65320b99e91a2b4e6e02/07_Python_01/PRG-08-Key-value%20pairs2.py

https://github.com/TechGrounds-Cloud8/cloud8-QuincyTjia/blob/8d669c3af700dc77de5b65320b99e91a2b4e6e02/07_Python_01/test.csv

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by sasudi90** [comment]
7.1 je hoeft de boolean (run) niet te declaren. https://www.delftstack.com/howto/python/python-while-true/
 
je hebt t ook meegekregen van de camelCase right ;)

**Comment by archana-sekarr** [comment]
Good job! your work shows you understand what you do.
